/**
 * @cq/config — cq.toml data model + parser/resolver (T170).
 *
 * Pure, typed module: parse a cq.toml document into a CqConfig, resolve its
 * `reviewers` aliases into ReviewerToken[], and load it from a repo root.
 * No MCP/transport concerns (that lands in T171).
 */

export type {
  Harness,
  ActiveHarness,
  ReviewerToken,
  CqConfig,
  WebuiConfig,
  Tier,
  TierEntry,
  TiersConfig,
  PiEffort,
  ClaudeEffort,
  CodexEffort,
  Effort,
  LedgerBackend,
  LedgerBackupMode,
  LedgerConfig,
  RemoteLedgerConfig,
  NonRemoteLedgerConfig,
  RemoteServerUrl,
  RemoteLedgerToken,
  ProjectConfig,
  DispatchConfig,
  UpstreamSwitch,
  UpstreamConfig,
} from "./types.js";
export {
  HARNESSES,
  isHarness,
  ACTIVE_HARNESSES,
  isActiveHarness,
  TIERS,
  isTier,
  DEFAULT_TIER,
  PI_EFFORTS,
  CLAUDE_EFFORTS,
  CODEX_EFFORTS,
  isEffort,
  LEDGER_BACKENDS,
  isLedgerBackend,
  LEDGER_BACKUP_MODES,
  isLedgerBackupMode,
  UPSTREAM_SWITCHES,
  isUpstreamSwitch,
} from "./types.js";
export {
  CQ_CONFIG_FILENAME,
  resolveConfigHome,
  resolveGlobalConfigPath,
  DEFAULT_REVIEWERS,
  DEFAULT_PLANNERS,
  DEFAULT_PANELS,
  defaultPanelFor,
  CqConfigError,
  parseReviewerToken,
  formatReviewerToken,
  reviewerTokensEqual,
  parseConfig,
  assertDispatchable,
  resolveReviewers,
  resolvePlanners,
  resolveAgentTier,
  tierModel,
  applyAgentEffort,
  resolveAgentModel,
  loadConfig,
} from "./config.js";
export type { DefaultPanel, DefaultPanelEntry } from "./config.js";
export type {
  DispatchTransport,
  DispatchTransportRouteRequest,
  DispatchTransportRoute,
  DispatchAdapterChildPort,
  DispatchAdapterLaunchContext,
  DispatchAdapterCompletion,
  DispatchAdapterAbortion,
  DispatchAdapterLaunchResult,
  DispatchAdapterLauncher,
  DispatchTransportAdapter,
  ClaudeProcessAdapterBinding,
  ClaudeProcessAdapterBindingResolver,
  CodexProcessAdapterBoundary,
  CodexProcessAdapterBinding,
  CodexProcessAdapterBindingResolver,
  RunPreparedDispatchRequest,
  RoutedDispatchConsumed,
  RoutedDispatchAborted,
  RoutedDispatchResult,
} from "./dispatchTransportRouter.js";
export {
  DISPATCH_TRANSPORTS,
  DispatchTransportRoutingError,
  DispatchTransportAbort,
  DispatchTransportAdapterRegistry,
  routeDispatchTransport,
  dispatchEffectTargetRef,
  createNativeDispatchAdapter,
  createClaudeProcessDispatchAdapter,
  createCodexProcessDispatchAdapter,
  createPiProcessDispatchAdapter,
  buildPositiveOnlyDispatchRegistry,
  runPreparedDispatch,
} from "./dispatchTransportRouter.js";
export type {
  NativeAdapterId,
  NativeQualificationRefusalReason,
  NativePathConfinementStrength,
  NativeAdapterQualified,
  NativeAdapterIncompatible,
  NativeAdapterQualification,
  EscapeCanaryObservation,
  PiNativeQualificationInput,
  ClaudeNativeQualificationInput,
  ClaudeNativeQualificationHandle,
  CodexProviderPreturnBinding,
  CodexProviderRoute,
  CodexProviderFailureControl,
  CodexProviderGateObservation,
  CodexProviderReleaseEvidence,
  CodexProviderGateAuthenticationInput,
  CodexNativeQualificationInput,
} from "./nativeDispatchQualification.js";
export {
  NATIVE_ADAPTER_IDS,
  CODEX_PROVIDER_PRETURN_BINDINGS,
  CODEX_PROVIDER_ROUTES,
  CODEX_PROVIDER_FAILURE_CONTROLS,
  NativeAdapterIncompatibilityError,
  isAbsoluteFilesystemPath,
  isManagedWorktreePath,
  qualifyClaudeNativeAdapter,
  authenticateCodexProviderGateObservation,
  qualifyCodexNativeAdapter,
  isAuthenticatedCodexNativeQualification,
  qualifyPiNativeAdapter,
  assertNativeAdapterQualified,
  selectQualifiedNativeAdapterIds,
  isNativeAdapterId,
  nativeAdapterIdFor,
} from "./nativeDispatchQualification.js";
export type {
  ManagedWorktreeHandle,
  ManagedWorktreeHandleV1,
  ManagedWorktreeHandleV2,
  ManagedWorktreeHandleValidation,
} from "./managedWorktreeHandle.js";
export {
  MANAGED_WORKTREE_HANDLE_KIND,
  isManagedWorktreeHandle,
  managedWorktreeHandlesEqual,
  validateManagedWorktreeHandle,
} from "./managedWorktreeHandle.js";
export type {
  ClaudeNativeManagedWorktreeHandle,
  ClaudeNativePreparedEvidence,
  ClaudeNativeWorktreePrepareResult,
  ClaudeNativeWorktreeReleaseResult,
  ClaudeNativeWorktreePreflightRequest,
  ClaudeNativeWorktreePreflightResult,
  ClaudeNativeWorktreeBinding,
  ClaudeNativeWorktreeBindResult,
  ClaudeNativeWorktreeManagePort,
} from "./claudeNativeWorktree.js";
export {
  ClaudeNativeWorktreeBindingError,
  preflightClaudeNativeWorktree,
  bindClaudeNativeWorktree,
  releaseClaudeNativeWorktree,
  assertClaudeNativeWorktreeBindingIntact,
  CLAUDE_NATIVE_WORKTREE_RELEASE_SEAM,
  CLAUDE_NATIVE_WORKTREE_PREPARE_SEAM,
} from "./claudeNativeWorktree.js";
export type {
  PiNativeManagedWorktreeHandle,
  PiNativePreparedEvidence,
  PiNativeWorktreePrepareResult,
  PiNativeWorktreeReleaseResult,
  PiNativeWorktreePreflightRequest,
  PiNativeWorktreePreflightResult,
  PiNativeWorktreeBinding,
  PiNativeWorktreeBindResult,
  PiNativeWorktreeManagePort,
} from "./piNativeWorktree.js";
export {
  PiNativeWorktreeBindingError,
  preflightPiNativeWorktree,
  bindPiNativeWorktree,
  releasePiNativeWorktree,
  assertPiNativeWorktreeBindingIntact,
  PI_NATIVE_WORKTREE_RELEASE_SEAM,
  PI_NATIVE_WORKTREE_PREPARE_SEAM,
} from "./piNativeWorktree.js";
export type {
  PiNativeSessionLaunchRequest,
  PiNativeSessionLaunchResult,
  PiNativeSessionLauncher,
  PiNativeAdapterBinding,
  PiNativeAdapterBindingResolver,
  CreatePiNativeDispatchAdapterOptions,
} from "./piNativeDispatch.js";
export {
  createPiNativeDispatchAdapter,
  selectPiChildDelivery,
  PI_NATIVE_SESSION_SEAM,
  PI_PROCESS_SESSION_SEAM,
} from "./piNativeDispatch.js";
export type {
  ClaudeNativeSessionLaunchRequest,
  ClaudeNativeSessionLaunchResult,
  ClaudeNativeSessionLauncher,
  ClaudeNativeAdapterBinding,
  ClaudeNativeAdapterBindingResolver,
  CreateClaudeNativeDispatchAdapterOptions,
} from "./claudeNativeDispatch.js";
export {
  createClaudeNativeDispatchAdapter,
  CLAUDE_NATIVE_SESSION_SEAM,
} from "./claudeNativeDispatch.js";
export {
  resolveActiveHarness,
  resolveActiveHarnessFromProcess,
  DEFAULT_HARNESS,
  CQ_HARNESS_ENV,
  CLAUDE_CODE_SESSION_ID_ENV,
} from "./activeHarness.js";
export type {
  RawToml,
  RawWebui,
  RawLedger,
  RawProject,
  RawDispatch,
  RawHarnessOverride,
} from "./toml.js";
export { parseToml } from "./toml.js";
export {
  CQ_LEDGER_REMOTE_TOKEN_ENV,
  CQ_LEDGER_REMOTE_ADMIN_TOKEN_ENV,
  RemoteLedgerTokenError,
  resolveRemoteLedgerToken,
  resolveRemoteLedgerTokenFromProcess,
  resolveRemoteAdminToken,
} from "./remoteToken.js";
export {
  WORKSET_CREDENTIAL_ENV_NAMES,
  withoutWorksetCredentials,
  createWorksetManagementCommand,
} from "./worksetManagementCommand.js";
export type {
  WorksetCredentialEnvName,
  WorksetManagementCommand,
} from "./worksetManagementCommand.js";
export type { AgentRoleTier } from "./agentRoster.js";
export { AGENT_ROLE_TIERS } from "./agentRoster.js";
export type {
  RoleKind,
  ModelTier,
  PromptSurface,
  IntentionalDifferenceKind,
  IntentionalDifferenceDeclaration,
  JSONSchema,
  JSONSchemaType,
  PromptCatalogEntry,
  RoleSchemaSidecar,
} from "./promptCatalog.js";
export {
  PROMPT_SURFACES,
  isPromptSurface,
  INTENTIONAL_DIFFERENCE_KINDS,
  isIntentionalDifferenceKind,
  INTENTIONAL_DIFFERENCE_DECLARATION_SCHEMA,
  PromptCatalogSchemaError,
  parseIntentionalDifferenceDeclaration,
  parseIntentionalDifferenceDeclarationJSON,
  serializeIntentionalDifferenceDeclaration,
} from "./promptCatalog.js";
export type {
  LedgerCapabilityToolName,
  RoleCapabilityClass,
  RoleToolCapabilityProfile,
  RoleCorpusObservation,
  LedgerToolProfileDecision,
  PiRoleToolDecision,
  PiRoleToolProfileManifest,
} from "./roleToolProfiles.js";
export {
  LEDGER_CAPABILITY_TOOL_NAMES,
  DISPATCH_RESULT_PLUMBING_TOOL_NAMES,
  DOMAIN_LEDGER_TOOL_NAMES,
  ROLE_CAPABILITY_CLASSES,
  ROLE_CAPABILITY_TOOLS,
  ROLE_TOOL_CAPABILITY_MATRIX,
  exposedLedgerToolsForRole,
  ledgerToolDecisionForRole,
  excludedLedgerToolsForRole,
  PI_ROLE_TOOL_PROFILE_MANIFEST_PATH,
  buildPiRoleToolProfileManifest,
  serializePiRoleToolProfileManifest,
  ROLE_IDENTIFIED_CORPUS,
  HARNESS_ROLE_TOOL_ENFORCEMENT,
  CODEX_ROLE_TOOL_PROFILE_PROBE,
} from "./roleToolProfiles.js";
export type {
  PromptFragmentSlot,
  PromptBlockClassification,
  PromptDispatchEdgeKind,
  PromptDispatchEdge,
  SharedPromptSourceBlock,
  FragmentPromptSourceBlock,
  PromptSourceBlock,
  PromptRoleSourceInventoryEntry,
  PromptFragmentSlotContract,
  ResolvedPromptFragmentInventoryEntry,
} from "./promptFragmentInventory.js";
export {
  PROMPT_FRAGMENT_SLOTS,
  PROMPT_BLOCK_CLASSIFICATIONS,
  PROMPT_DISPATCH_EDGE_KINDS,
  PROMPT_FRAGMENT_SLOT_CONTRACTS,
  PROMPT_ROLE_SOURCE_INVENTORY,
  PROMPT_FRAGMENT_INVENTORY,
  validatePromptFragmentInventory,
} from "./promptFragmentInventory.js";
export type {
  DispatchFlowFamily,
  InventoryDispatchEdgeKind,
  PromptSiteKind,
  PromptSiteClass,
  CatalogDispatchRelation,
  CatalogInventoryRole,
  SurfaceLifecycle,
  DispatchEdgeRecord,
  RecursionEdgeRecord,
  InventoryEdge,
  ClassifiedPromptSite,
  DispatchEdgeInventory,
} from "./dispatchEdgeInventory.js";
export {
  DISPATCH_FLOW_FAMILIES,
  DISPATCH_EDGE_KINDS,
  PROMPT_SITE_KINDS,
  PROMPT_SITE_CLASSES,
  RefFirstInventoryError,
  buildDispatchEdgeInventory,
  DISPATCH_EDGE_INVENTORY,
  planReviewDispatchEdges,
  investigateResearchDispatchEdges,
  implementDispatchEdges,
  recursionEdges,
  inspectionSites,
} from "./dispatchEdgeInventory.js";
export type {
  DispatchLifecycleKind,
  DispatchLifecycleOutcomeKind,
  DispatchLifecycleAttribution,
  DispatchLifecycleTerminal,
  DispatchLifecycleLog,
  DispatchLifecycleEvent,
} from "./dispatchLifecycleLog.js";
export {
  DISPATCH_LIFECYCLE_LOG_KIND,
  DISPATCH_LIFECYCLE_LOG_VERSION,
  DISPATCH_LIFECYCLE_KINDS,
  DISPATCH_LIFECYCLE_OUTCOME_KINDS,
  LifecycleLogError,
  assertDispatchLifecycleLogSafe,
  foldDispatchLifecycleEvents,
} from "./dispatchLifecycleLog.js";
export type {
  TelemetryPhase,
  TelemetryUnit,
  TelemetryOwner,
  MeasuredQuantity,
  UnavailableQuantity,
  TelemetryQuantity,
  LabeledResearchMeasurement,
  DispatchTelemetryRecord,
  HostTelemetryFixture,
} from "./dispatchTelemetry.js";
export {
  DISPATCH_TELEMETRY_KIND,
  DISPATCH_TELEMETRY_VERSION,
  TELEMETRY_PHASES,
  TELEMETRY_UNITS,
  TELEMETRY_OWNERS,
  TelemetryContractError,
  buildDispatchTelemetry,
  unavailable,
  measured,
  mapHostTelemetryFixture,
} from "./dispatchTelemetry.js";
export type {
  PromptCatalogFileInput,
  PromptFragmentFileInput,
  RenderPromptSurfaceTreeInput,
  RenderedPromptArtifact,
  RenderedPromptSurfaceTree,
  PromptSurfaceRoleAttestation,
  PromptSurfaceManifestCoreField,
  PromptSurfaceManifestField,
  PromptSurfaceRoleAttestationField,
  PromptSurfaceManifestCore,
  PromptSurfaceManifest,
} from "./promptRenderer.js";
export {
  PROMPT_SURFACE_MANIFEST_CORE_FIELDS,
  PROMPT_SURFACE_MANIFEST_FIELDS,
  PROMPT_SURFACE_ROLE_ATTESTATION_FIELDS,
  serializePromptSurfaceManifestCore,
  serializePromptSurfaceManifest,
  PromptRendererError,
  renderPromptSurfaceTree,
} from "./promptRenderer.js";
export type {
  PackagedPromptSurfaceRoleArtifact,
  PackagedPromptSurfaceInput,
} from "./packagedPromptSurface.js";
export {
  PackagedPromptSurfaceError,
  validatePackagedPromptSurface,
  validatePackagedPromptSurfaceRoot,
} from "./packagedPromptSurface.js";
export type {
  PromptVerificationRoot,
  PromptFragmentObservation,
  PromptCatalogVerificationInput,
} from "./promptCatalogVerification.js";
export {
  PromptCatalogVerificationError,
  verifyPromptCatalog,
} from "./promptCatalogVerification.js";
export { planAdvanceSidecar, PLAN_STEP_ACTIONS } from "./schemas/plan-advance.js";
export { planReviewerSidecar, PLAN_REVIEW_VERDICTS } from "./schemas/plan-reviewer.js";
export {
  implementWorkerSidecar,
  IMPLEMENT_WORKER_STATUSES,
  IMPLEMENT_WORKER_FULL_SHA_PATTERN,
  IMPLEMENT_WORKER_CANONICAL_GATE_COMMAND,
  IMPLEMENT_WORKER_SUPERVISED_GATE_KIND,
  IMPLEMENT_WORKER_BASE_UNRESOLVABLE_REASONS,
  TEST_GUARD_GLOBS,
  implementWorkerBaseVerificationSchema,
  implementWorkerVerifiedBaseVerificationSchema,
  implementWorkerUnresolvableBaseVerificationSchema,
  implementWorkerSupervisedGateEvidenceSchema,
} from "./schemas/implement-worker.js";
export type {
  ImplementWorkerBaseUnresolvableReason,
  ImplementWorkerSupervisedGateEvidence,
} from "./schemas/implement-worker.js";
export {
  implementReviewerSidecar,
  IMPLEMENT_REVIEW_VERDICTS,
  IMPLEMENT_REVIEWER_PHASE_EXHAUSTION_CRITICISM,
  IMPLEMENT_REVIEWER_FULL_SHA_PATTERN,
  IMPLEMENT_REVIEWER_RESULT_COMMIT_UNRESOLVABLE_REASONS,
  IMPLEMENT_REVIEWER_BASE_ANCESTRY_UNRESOLVABLE_REASONS,
  SANDBOX_DENIED_PRIMITIVES_GATE_REASON,
  validateParentGateAttestation,
  validateSupervisedWorkerGateEvidenceForReview,
  implementReviewerResultCommitEvidenceSchema,
  implementReviewerBaseAncestrySchema,
  implementReviewerVerifiedResultCommitEvidenceSchema,
  implementReviewerVerifiedBaseAncestrySchema,
} from "./schemas/implement-reviewer.js";
export type {
  ParentGateAttestation,
  ImplementReviewerResultCommitUnresolvableReason,
  ImplementReviewerBaseAncestryUnresolvableReason,
} from "./schemas/implement-reviewer.js";
export {
  implementConflictResolverSidecar,
  CONFLICT_RESOLVER_STATUSES,
} from "./schemas/implement-conflict-resolver.js";
export { investigateExplorerSidecar } from "./schemas/investigate-explorer.js";
export { investigateProberSidecar } from "./schemas/investigate-prober.js";
export { EVIDENCE_LEANS } from "./schemas/investigate-evidence.js";
export {
  DISPATCHED_ROLE_SIDECARS,
  DISPATCHED_ROLE_IDS,
  DISPATCHED_ROLE_VERSIONS,
  getRoleSidecar,
} from "./promptCatalogStore.js";
export type { ValidationError, ValidationResult } from "./validation.js";
export { validateAgainstSchema } from "./validation.js";
export type { WipArtifactCheckpoint, WipArtifact, WipCheckpointStatus } from "./wipArtifact.js";
export {
  WIP_CHECKPOINT_STATUSES,
  WipArtifactParseError,
  parseWipArtifact,
  serializeWipArtifact,
} from "./wipArtifact.js";
export type {
  DispatchedRoleId,
  DispatchJSONValue,
  DispatchOverlayApplication,
  CompactDispatchLaunch,
  DispatchHandle,
  InputCapability,
  GitChangeCapability,
  GitConflictCapability,
  ResultCapability,
  ParentGateCapability,
  DispatchPromptProvenance,
  DispatchDeadlines,
  DispatchPrepared,
  FetchDispatchInput,
  MaterializedDispatchInput,
  StoreDispatchResult,
  NativeCompletionProof,
  ConfirmDispatchCompletion,
  DispatchAbortReason,
  AbortDispatch,
  DispatchLifecycleState,
  FetchDispatchResultState,
  PreparedDispatchResult,
  GatePendingDispatchResult,
  ResultStoredDispatchResult,
  ConsumedDispatchResult,
  AbortedDispatchResult,
  TerminalEnvelopeExpiredDispatchResult,
  AttestationNotFoundDispatchResult,
  OutputAlreadyMaterializedDispatchResult,
  FetchDispatchResult,
  DispatchProtocolOperation,
} from "./compactDispatchProtocol.js";
export {
  DISPATCH_ABORT_REASONS,
  DISPATCH_LIFECYCLE_STATES,
  FETCH_DISPATCH_RESULT_STATES,
  DISPATCH_PROTOCOL_OPERATIONS,
  DISPATCH_UTC_TIMESTAMP_PATTERN,
  COMPACT_DISPATCH_LAUNCH_SCHEMA,
  compactDispatchLaunchSchemaFor,
  DISPATCH_HANDLE_SCHEMA,
  DISPATCH_PREPARED_SCHEMA,
  FETCH_DISPATCH_INPUT_SCHEMA,
  MATERIALIZED_DISPATCH_INPUT_SCHEMA,
  STORE_DISPATCH_RESULT_SCHEMA,
  CONFIRM_DISPATCH_COMPLETION_SCHEMA,
  ABORT_DISPATCH_SCHEMA,
  FETCH_DISPATCH_RESULT_SCHEMA,
} from "./compactDispatchProtocol.js";
export type {
  DispatchOverlayDefinition,
  DispatchOverlayRegistry,
  DispatchPromptMaterializationInput,
  DispatchPromptMaterialization,
} from "./dispatchOverlays.js";
export {
  DispatchOverlayError,
  createDispatchOverlayRegistry,
  DISPATCH_OVERLAY_REGISTRY,
  dispatchOverlayListSchema,
  materializeDispatchPrompt,
  validateDispatchOverlayApplications,
} from "./dispatchOverlays.js";
export type {
  DispatchPreLaunchRejectionReason,
  DispatchPreLaunchRejection,
  PreLaunchRejectionOutcomeIsNotALifecycleState,
  DispatchInputAccepted,
  DispatchInputValidation,
  DispatchPrepareStep,
  ValidateInputInspectionCaller,
  DispatchOutcomeTagClass,
  ChildSideValidationException,
  ChildSideValidationExceptionRegistry,
  DispatchInputValidatorPlacement,
  DispatchInputValidatorClaim,
  InsidePrepareValidatorResolution,
  ChildSideValidatorResolution,
  DispatchInputValidatorResolution,
  DispatchInputValidationRequest,
} from "./dispatchInputValidation.js";
export {
  DispatchInputValidationError,
  DISPATCH_PRE_LAUNCH_OUTCOME,
  DISPATCH_PRE_LAUNCH_REJECTION_REASONS,
  DISPATCH_INPUT_VALIDATION_PLACEMENT,
  DISPATCH_PREPARE_VALIDATION_STEPS,
  DISPATCH_PREPARE_ALLOCATION_STEPS,
  DISPATCH_PREPARE_STEP_ORDER,
  assertValidateThenAllocate,
  RETAINED_NON_FLOW_MCP_VALIDATORS,
  RETAINED_INSPECTION_VALIDATORS,
  VALIDATE_INPUT_INSPECTION_CALLERS,
  isAllowlistedValidateInputCaller,
  classifyDispatchOutcomeTag,
  isDispatchPreLaunchRejection,
  createChildSideValidationExceptionRegistry,
  CHILD_SIDE_VALIDATION_EXCEPTIONS,
  DISPATCH_INPUT_VALIDATOR_PLACEMENTS,
  resolveDispatchInputValidator,
  validateDispatchInput,
  DISPATCH_INPUT_VALIDATION_DEFERRED_TO,
  DISPATCH_INPUT_VALIDATION_DEFERRED,
  dispatchPreLaunchRejection,
} from "./dispatchInputValidation.js";
export type {
  DispatchWorktreeCoordinates,
  ParentGuidanceKind,
  AnsweredQuestionGuidance,
  OperatorNoteGuidance,
  ParentGuidance,
  DispatchInputRefs,
  RefAssembledRoleId,
  CompactDispatchRefsLaunch,
  DispatchNarrativeItem,
  DispatchNarrativeSource,
  DispatchInputAssembled,
  DispatchInputAssembly,
  DispatchAssemblyContext,
} from "./dispatchRefAssembly.js";
export {
  DispatchRefAssemblyError,
  canonicalDispatchInputBytes,
  dispatchInputDigest,
  REFS_SUPPLIED_INPUT_FIELDS,
  ASSEMBLED_NARRATIVE_FIELDS,
  readNarrativeField,
  assembledNarrativeFieldsFor,
  PARENT_GUIDANCE_KINDS,
  PARENT_GUIDANCE_MAX_ENTRIES,
  PARENT_GUIDANCE_NOTE_MAX_LENGTH,
  DISPATCH_INPUT_REFS_FIELDS,
  REF_ASSEMBLED_ROLES,
  REF_ASSEMBLER_COVERAGE,
  DISPATCH_INPUT_REFS_SCHEMA,
  compactDispatchRefsLaunchSchemaFor,
  COMPACT_DISPATCH_REFS_LAUNCH_SCHEMA,
  REF_ASSEMBLY_LEDGERS,
  foldAnsweredQuestion,
  foldOperatorNote,
  assembleDispatchInput,
  isDispatchInputAssembled,
  ROLE_PROMPT_RETRIEVAL_OPERATIONS,
  NATIVE_CLAUDE_CHILD_RETRIEVAL,
  assertNoRolePromptRetrieval,
  DISPATCH_REF_ASSEMBLY_DEFERRED_TO,
  DISPATCH_REF_ASSEMBLY_DEFERRED,
} from "./dispatchRefAssembly.js";
export type {
  AttestationNamespace,
  AttestationNamespaceBackend,
  DispatchAuthorizationScope,
  TrustedDispatchActor,
  StoreResultCannotName,
  DispatchRandomBytes,
  AttestationEnvelopeState,
  AttestationTerminalKind,
  NativeChildIdentity,
  DispatchProvenanceBinding,
  DispatchGitEffectBinding,
  DispatchGuardedRebaseBridge,
  AuthorizedDispatchGitEffect,
  AuthorizedSupervisedWorkerGateContext,
  AttestationEnvelope,
  AttestationTombstone,
  AttestationRow,
  AttestationSweepReport,
  AttestationStore,
  DispatchNow,
  DispatchServiceDeps,
  PrepareDispatchDeps,
  PrepareDispatchRequest,
  DispatchPrepareAccepted,
  PrepareDispatchOutcome,
  StoreDispatchResultOutcome,
  StoredDispatchResultView,
  GatePendingResultView,
  ParentGateFinalizeRequest,
  ClaimedParentGate,
  ClaimParentGateOutcome,
  CompleteParentGateRequest,
  InvalidOutputAbortDetails,
  ConfirmDispatchCompletionRequest,
  ConfirmDispatchCompletionOutcome,
  ConfirmedDispatchResultView,
  FetchDispatchResultRequest,
  FetchDispatchInputRequest,
  AbortDispatchRequest,
  AuthorizeDispatchGitEffectRequest,
  AuthorizeDispatchGitConflictRequest,
} from "./dispatchAttestation.js";
export {
  AttestationContractError,
  AttestationNamespaceError,
  DispatchAuthorizationError,
  AttestationBindingError,
  AttestationNotFoundError,
  DispatchStateConflictError,
  AttestationStorageError,
  AttestationTransportError,
  AttestationKeyReuseError,
  ATTESTATION_ERROR_CLASSES,
  isAttestationDomainError,
  assertAttestationNamespace,
  attestationNamespacesEqual,
  formatAttestationNamespace,
  TERMINAL_ENVELOPE_RETENTION_MS,
  IDEMPOTENCY_HORIZON_MS,
  DISPATCH_TIMEOUT_MIN_MS,
  DISPATCH_TIMEOUT_MAX_MS,
  RESPONSE_STORE_LEAD_MS,
  LAUNCH_DEADLINE_MS,
  IMPLEMENT_REVIEWER_SYNTHESIS_STORE_RESERVE_MS,
  IMPLEMENT_REVIEWER_TIMEOUT_MIN_MS,
  IMPLEMENT_REVIEWER_TIMING_INPUT_FIELDS,
  ATTESTATION_ID_ENTROPY_BYTES,
  RESULT_CAPABILITY_ENTROPY_BYTES,
  PARENT_GATE_CAPABILITY_ENTROPY_BYTES,
  INPUT_CAPABILITY_ENTROPY_BYTES,
  GIT_CHANGE_CAPABILITY_ENTROPY_BYTES,
  GIT_CONFLICT_CAPABILITY_ENTROPY_BYTES,
  DISPATCH_AUTHORIZATION_SCOPES,
  TRUSTED_DISPATCH_ACTORS,
  DISPATCH_OPERATION_AUTHORIZATION,
  DISPATCH_OPERATION_AUTHORIZATION_COVERAGE,
  assertDispatchOperationAuthorization,
  RESULT_CAPABILITY_OPERATIONS,
  INPUT_CAPABILITY_OPERATIONS,
  GIT_CHANGE_CAPABILITY_OPERATIONS,
  GIT_CONFLICT_CAPABILITY_OPERATIONS,
  dispatchOperationScope,
  resultCapabilityAuthorizes,
  inputCapabilityAuthorizes,
  gitChangeCapabilityAuthorizes,
  gitConflictCapabilityAuthorizes,
  dispatchPayloadDigest,
  resultCapabilityHash,
  resultCapabilityMatches,
  parentGateCapabilityHash,
  parentGateCapabilityMatches,
  inputCapabilityHash,
  inputCapabilityMatches,
  gitChangeCapabilityHash,
  gitChangeCapabilityMatches,
  gitConflictCapabilityHash,
  gitConflictCapabilityMatches,
  defaultDispatchRandomBytes,
  mintAttestationId,
  mintResultCapability,
  mintParentGateCapability,
  mintInputCapability,
  mintGitChangeCapability,
  mintGitConflictCapability,
  ATTESTATION_ENVELOPE_STATES,
  TOMBSTONE_RETAINED_FIELDS,
  TOMBSTONE_FORBIDDEN_FIELDS,
  isAttestationTombstone,
  attestationRowDigest,
  attestationInstantMs,
  assertDispatchHandle,
  prepareDispatch,
  prepareDispatchRequestDigest,
  fetchDispatchInput,
  authorizeDispatchGitEffect,
  authorizeDispatchGitConflict,
  gitEffectBindingForResultCapability,
  supervisedWorkerGateContextForResultCapability,
  claimParentGate,
  completeParentGate,
  gitEffectBindingForHandle,
  storeDispatchResult,
  invalidOutputDetailsOf,
  confirmDispatchCompletion,
  provenanceBindingOf,
  abortDispatch,
  fetchDispatchResult,
  isBackendOwnedConsumedDispatchResult,
  isBackendOwnedAbortedDispatchResult,
  collapseAttestationEnvelope,
  sweepAttestations,
  DISPATCH_ATTESTATION_DEFERRED_TO,
  DISPATCH_ATTESTATION_DEFERRED,
  DISPATCH_ATTESTATION_MCP_DEFERRED_TO,
} from "./dispatchAttestation.js";
// --- T690: the Codex-surface binding of the compact dispatch protocol ------
export type {
  CodexDeliveryMode,
  CodexDeliveryModeVerdict,
  CodexChildCorrelation,
  CodexLaunchRefusal,
  CodexLaunchApproved,
  CodexLaunchRefused,
  CodexLaunchVerdict,
  CodexFinalMessageVerdictKind,
  CodexFinalMessageVerdict,
  CodexChildOutcome,
  CodexExitCorroboration,
  CodexCompletionObservation,
  CodexConfirmDecision,
  CodexAbortDecision,
  CodexCompletionDecision,
  CodexCompletionRequest,
} from "./codexDispatchProtocol.js";
export {
  CodexUnsupportedModeError,
  CodexObservationProvenanceError,
  CODEX_DELIVERY_MODE_IDS,
  CODEX_DELIVERY_MODES,
  SUPPORTED_CODEX_DELIVERY_MODES,
  UNSUPPORTED_CODEX_DELIVERY_MODES,
  CODEX_NATIVE_DELIVERY_MODE,
  CODEX_FALLBACK_DELIVERY_MODE,
  isSupportedCodexDeliveryMode,
  assertSupportedCodexDeliveryMode,
  codexCompletionActor,
  CODEX_ROLE_DELIVERY_PREREQUISITES,
  CODEX_ROLE_DELIVERY_PREREQUISITES_ARE_ATOMIC,
  CODEX_ROLE_DELIVERY_PREREQUISITES_APPLIED,
  CODEX_ROLE_DELIVERY_MIGRATION_OWNER,
  CODEX_GLOBAL_AGENTS_DIR,
  CODEX_NATIVE_AGENT_DECLARATION_KEYS,
  CODEX_CORRELATION_ENTROPY_BYTES,
  CODEX_CORRELATION_SEPARATOR,
  mintCodexCorrelationId,
  assertCodexChildCorrelation,
  codexExpectedChild,
  CODEX_LAUNCH_REFUSALS,
  codexLaunchGate,
  CODEX_FINAL_MESSAGE_VERDICTS,
  classifyCodexFinalMessage,
  CODEX_CHILD_OUTCOMES,
  CODEX_EXIT_CORROBORATIONS,
  decideCodexCompletion,
  codexExitCorroboration,
  CODEX_DISPATCH_DEFERRED_TO,
  CODEX_DISPATCH_DEFERRED,
} from "./codexDispatchProtocol.js";
export type {
  CodexRoleSandboxMode,
  CodexRoleSandboxPolicyResolution,
  CodexRoleBoundaryRequest,
  CodexRoleBoundaryInvocation,
  CodexRoleLedgerMcpConfiguration,
  CodexRoleBoundaryPlan,
  CodexRoleBoundaryExecutionResult,
  CodexRoleBoundaryWorksetEffect,
  CodexEffectivePreturn,
  CodexInstalledIdentity,
  CodexInstalledRoleBoundaryExecution,
  CodexInstalledRoleBoundaryRequest,
  CodexProviderSandboxControl,
  CodexProviderSandboxControlRequest,
  CodexProviderSandboxControlRoute,
  CodexRoleBoundaryDiagnosticVerdict,
  CodexRoleBoundaryDiagnosticDetailCode,
  CodexRoleBoundaryDiagnostic,
  CodexBrokeredStoreResultOutcome,
  CodexParentGateFinalizerRequest,
} from "./codexRoleBoundary.js";
export {
  CODEX_ROLE_SANDBOX_MODES,
  CODEX_ROLE_BOUNDARY_DIAGNOSTIC_PREFIX,
  CODEX_ROLE_BOUNDARY_DIAGNOSTIC_VERDICTS,
  CODEX_ROLE_BOUNDARY_DIAGNOSTIC_DETAIL_CODES,
  CODEX_BROKERED_STORE_RESULT_OUTCOMES,
  CODEX_PRETURN_OBSERVATION_PATH_ENV,
  CODEX_PARENT_GATE_TERMINATION_GRACE_MS,
  CodexRoleBoundaryError,
  CodexBrokeredStoreResultError,
  CodexOperationalAbstentionError,
  formatCodexRoleBoundaryDiagnostic,
  assertCodexBoundaryEffectTargetRef,
  assertCodexDispatchedRoleId,
  resolveCodexRoleSandboxPolicy,
  createCodexRoleBoundaryPlan,
  interceptCodexRoleBoundaryResult,
  executeCodexRoleBoundary,
  executeCodexParentGateFinalizer,
  executeInstalledCodexRoleBoundary,
  executeCodexProviderSandboxControl,
  isRunnerOwnedCodexRoleBoundaryExecution,
  isRunnerOwnedCodexInstalledRoleBoundaryExecution,
  isRunnerOwnedCodexProviderSandboxControl,
} from "./codexRoleBoundary.js";
export type {
  CodexStagedTimingBasis,
  CodexStagedTimingPhase,
  CodexStagedTimingPhaseName,
} from "./codexStagedTiming.js";
export {
  CODEX_STAGED_TIMING_BASIS,
  CODEX_STAGED_TIMING_PHASE_NAMES,
  CODEX_STAGED_TIMING_PHASES,
  calculateCodexParentFirstAttemptMs,
  calculateCodexStagedTimingBasis,
} from "./codexStagedTiming.js";
export type {
  CodexSandboxPipeProbeVerdict,
  CodexSandboxPipeProbeRequest,
  CodexSandboxPipeProbeReport,
} from "./codexSandboxPreflight.js";
export {
  CODEX_SANDBOX_PIPE_PROBE_VERDICTS,
  CODEX_REVIEWER_ROLE_SUFFIX,
  CODEX_READ_ONLY_SANDBOX_TMPDIR,
  CODEX_SANDBOX_PIPE_PROBE_TIMEOUT_MS,
  SandboxPipeProbeError,
  requiresCodexSandboxPreflight,
  runCodexSandboxPipeProbe,
  renderSandboxTmpdirOverride,
  argvWithSandboxTmpdir,
} from "./codexSandboxPreflight.js";

export type {
  ClaudeDeliveryMode,
  ClaudeDeliveryModeVerdict,
  ClaudeDispatcherClass,
  ClaudeEnforcementStrength,
  ClaudeContainmentProfile,
  ClaudeChildCorrelation,
  ClaudeCorrelationProvenance,
  ClaudeLaunchRefusal,
  ClaudeLaunchApproved,
  ClaudeLaunchRefused,
  ClaudeLaunchVerdict,
  ClaudeFinalMessageVerdictKind,
  ClaudeFinalMessageVerdict,
  ClaudeTerminalSignal,
  ClaudeChildOutcome,
  ClaudeExitCorroboration,
  ClaudeCompletionObservation,
  ClaudeConfirmDecision,
  ClaudeAbortDecision,
  ClaudeCompletionDecision,
  ClaudeCompletionRequest,
  ClaudeWorktreePlacement,
} from "./claudeDispatchProtocol.js";
export {
  ClaudeUnsupportedModeError,
  ClaudeObservationProvenanceError,
  CLAUDE_DELIVERY_MODE_IDS,
  CLAUDE_DELIVERY_MODES,
  SUPPORTED_CLAUDE_DELIVERY_MODES,
  UNSUPPORTED_CLAUDE_DELIVERY_MODES,
  CLAUDE_NATIVE_DELIVERY_MODE,
  CLAUDE_CROSS_HARNESS_DELIVERY_MODE,
  CLAUDE_DISPATCHER_CLASSES,
  CLAUDE_ENFORCEMENT_STRENGTHS,
  isSupportedClaudeDeliveryMode,
  assertSupportedClaudeDeliveryMode,
  claudeDeliveryModeFor,
  claudeCompletionActor,
  CLAUDE_CONTAINMENT_PROFILES,
  claudeContainmentProfile,
  CLAUDE_ACCEPTED_RESIDUALS,
  CLAUDE_D263_WORKTREE_CONFINEMENT_INCOMPATIBILITY,
  CLAUDE_RESIDUAL_ACCEPTANCE_QUOTE,
  CLAUDE_NATIVE_ENFORCEMENT_GAP,
  CLAUDE_NATIVE_REGISTRATION_POLICY,
  CLAUDE_CORRELATION_ENTROPY_BYTES,
  CLAUDE_CORRELATION_SEPARATOR,
  CLAUDE_CORRELATION_PROVENANCES,
  mintClaudeLaunchNonce,
  assertClaudeChildCorrelation,
  claudeCorrelationProvenance,
  claudeExpectedChild,
  CLAUDE_LAUNCH_REFUSALS,
  claudeLaunchGate,
  CLAUDE_FINAL_MESSAGE_VERDICTS,
  classifyClaudeFinalMessage,
  CLAUDE_COMPLETED_TERMINAL_REASON,
  claudeTerminalOutcome,
  CLAUDE_CHILD_OUTCOMES,
  CLAUDE_EXIT_CORROBORATIONS,
  claudeChildOutcome,
  decideClaudeCompletion,
  claudeExitCorroboration,
  CLAUDE_WORKTREE_PLACEMENTS,
  CLAUDE_MODE_WORKTREE_PLACEMENTS,
  claudeWorktreePlacement,
  CLAUDE_WORKTREE_INPUT_PROPERTY,
  CLAUDE_WORKTREE_OUTPUT_PROPERTY,
  CLAUDE_NATIVE_ISOLATION_ARGUMENT,
  CLAUDE_NATIVE_RUN_IN_BACKGROUND_ARGUMENT,
  CLAUDE_WORKTREE_ADDRESSING,
  CLAUDE_WORKTREE_RECONCILIATION,
  CLAUDE_WORKTREE_RESUME_IS_BY_HANDLE,
  CLAUDE_FETCH_SEMANTICS_ASSUMED,
  CLAUDE_DISPATCH_DEFERRED_TO,
  CLAUDE_DISPATCH_PROVEN_BY,
  CLAUDE_DISPATCH_DEFERRED,
} from "./claudeDispatchProtocol.js";
export type {
  ClaudeNativeLaunchEnvelope,
  ClaudeCompactLaunchRequest,
  ClaudeNativeLaunchContext,
  ClaudeNativeLaunchReport,
  ClaudeNativeLauncher,
  ClaudePrintStoreServer,
  ClaudePrintLaunchOptions,
  ClaudeParentCompletion,
  ClaudeTransportProvenance,
  ClaudeDispatchMaterializer,
  ClaudeParentCompletionCarriesNoBody,
  ClaudeDispatchRunOutcome,
  ClaudeDispatchRejected,
  ClaudeDispatchAborted,
  ClaudeDispatchConsumed,
  ClaudeDispatchRun,
  ClaudeDispatchRequest,
  ClaudeBridgeDeps,
  ClaudeSettleContext,
  ClaudeArtifactViolation,
  ClaudeArtifactFinding,
} from "./claudeDispatchBridge.js";
export {
  CLAUDE_DISPATCH_RUN_OUTCOMES,
  CLAUDE_ARTIFACT_VIOLATIONS,
  CLAUDE_ARTIFACT_INSPECTION_TOKEN,
  scanClaudeRefFirstArtifact,
  claudeArtifactViolations,
  assertClaudeRefFirstArtifact,
  CLAUDE_REF_FIRST_ARTIFACTS,
  runClaudeNativeDispatch,
  recoverClaudeNativeDispatch,
  launchClaudePrint,
  launchClaudePrintAsync,
  createClaudeDispatchMaterializer,
  CLAUDE_COMPACT_LAUNCH_PROMPT_MAX_BYTES,
  claudeCompactLaunchPrompt,
  buildClaudeCompactNativeLaunch,
  assertCompactClaudeLaunchPrompt,
  CLAUDE_BRIDGE_MODE,
  assertClaudeBridgeMode,
  claudeBridgeCorrelation,
  CLAUDE_BRIDGE_DEFINED_BY,
  CLAUDE_BRIDGE_PROVEN_BY,
  CLAUDE_BRIDGE_FETCH_COUNT,
  CLAUDE_BRIDGE_DEFERRED,
} from "./claudeDispatchBridge.js";

export type {
  AttestationStoreOperation,
  AttestationStoreFault,
} from "./dispatchAttestationDummy.js";
export {
  ATTESTATION_STORE_OPERATIONS,
  InMemoryAttestationStore,
  InMemoryAttestationBackend,
  FakeDispatchClock,
  sequentialDispatchRandomBytes,
} from "./dispatchAttestationDummy.js";

// --- T720: the namespaced production AttestationStore adapters -------------
export { AsyncMutex } from "./asyncMutex.js";
export type {
  AttestationStoreBackend,
  AttestationExcludedBackend,
  AttestationLoadScope,
  AttestationLoadScopeKind,
  AttestationJournalEntry,
  AttestationBackend,
  AttestationBackendIO,
  AttestationBackendDeps,
  AttestationBackendPrepareDeps,
  AttestationSweepTimer,
  AttestationSweepScheduleOptions,
  PersistedAttestationRow,
} from "./dispatchAttestationBackend.js";
export {
  ATTESTATION_STORE_BACKENDS,
  ATTESTATION_EXCLUDED_BACKENDS,
  ATTESTATION_EXCLUSION_REASONS,
  ATTESTATION_IN_MEMORY_BACKEND,
  ATTESTATION_BACKEND_COVERAGE,
  ATTESTATION_DEFERRAL_DISCHARGE,
  ATTESTATION_DEFERRAL_COVERAGE,
  assertAttestationDeferralDischarge,
  ATTESTATION_LOAD_SCOPE_KINDS,
  ATTESTATION_TABLE,
  PERSISTED_ATTESTATION_COLUMNS,
  AttestationBackendUnsupportedError,
  AttestationSweepScheduler,
  BufferedAttestationStore,
  abortDispatchOn,
  applyJournalToStore,
  assertAttestationBackendCoverage,
  assertAttestationStoreBackend,
  assertAttestationStoreNamespace,
  attestationStorageKey,
  confirmDispatchCompletionOn,
  claimParentGateOn,
  completeParentGateOn,
  defaultAttestationSweepTimer,
  fetchDispatchResultOn,
  consumedResultsComeFromDifferentBackendInstances,
  fetchDispatchInputOn,
  authorizeDispatchGitEffectOn,
  authorizeDispatchGitConflictOn,
  resolveDispatchGitEffectBindingOn,
  resolveSupervisedWorkerGateContextOn,
  resolveDispatchGitEffectBindingForHandleOn,
  formatAttestationNamespaceLockKey,
  handleLoadScope,
  journalEntryHandle,
  loadScopeFromStore,
  persistAttestationRow,
  prepareDispatchOn,
  prepareLoadScope,
  rehydrateAttestationRow,
  runAttestationUnitOfWork,
  storeDispatchResultOn,
  storeResultLoadScope,
  sweepAttestationsOn,
} from "./dispatchAttestationBackend.js";
export type {
  SqliteAttestationBackendOptions,
  SqliteAttestationConnection,
} from "./dispatchAttestationSqlite.js";
export {
  ATTESTATION_BUSY_TIMEOUT_MS,
  ATTESTATION_DB_FILENAME,
  SqliteAttestationBackend,
  SqliteAttestationConnectionRegistry,
  asSqliteBackendError,
  defaultSqliteAttestationConnectionRegistry,
  ensureAttestationSchema,
  resolveAttestationDbKey,
  xdgAttestationDbPath,
  xdgAttestationStateBase,
} from "./dispatchAttestationSqlite.js";
export type { FsAttestationBackendOptions } from "./dispatchAttestationFs.js";
export {
  ATTESTATION_LOCKS_DIR,
  ATTESTATION_LOCK_POLL_MS,
  ATTESTATION_LOCK_TIMEOUT_MS,
  FsAttestationBackend,
  asFsBackendError,
  fsAttestationNamespaceDir,
  fsAttestationRowFileContent,
  fsAttestationRowPath,
} from "./dispatchAttestationFs.js";
export type {
  ExpectedFailureInventoryEntry,
  ExpectedFailureSource,
  ExpectedFailureMarker,
} from "./expectedFailurePolicy.js";
export {
  ExpectedFailurePolicyError,
  enumerateExpectedFailureSourceFiles,
  readExpectedFailureSources,
  scanExpectedFailures,
} from "./expectedFailurePolicy.js";
export { EXPECTED_FAILURE_INVENTORY } from "./expectedFailureInventory.js";
export type { PostgresAttestationBackendOptions } from "./dispatchAttestationPostgres.js";
export {
  PostgresAttestationBackend,
  asPgBackendError,
  ensurePgAttestationSchema,
  openAttestationPgPool,
} from "./dispatchAttestationPostgres.js";
