/**
 * @cq/config — cq.toml data model + parser/resolver (T170).
 *
 * Pure, typed module: parse a cq.toml document into a CqConfig, resolve its
 * `reviewers` aliases into ReviewerToken[], and load it from a repo root.
 * No MCP/transport concerns (that lands in T171).
 */

export type {
  Harness,
  ActiveHarness,
  ReviewerToken,
  CqConfig,
  WebuiConfig,
  Tier,
  TierEntry,
  TiersConfig,
  PiEffort,
  ClaudeEffort,
  Effort,
  LedgerBackend,
  LedgerBackupMode,
  LedgerConfig,
  RemoteLedgerConfig,
  NonRemoteLedgerConfig,
  RemoteServerUrl,
  RemoteLedgerToken,
  ProjectConfig,
} from "./types.js";
export {
  HARNESSES,
  isHarness,
  ACTIVE_HARNESSES,
  isActiveHarness,
  TIERS,
  isTier,
  DEFAULT_TIER,
  PI_EFFORTS,
  CLAUDE_EFFORTS,
  isEffort,
  LEDGER_BACKENDS,
  isLedgerBackend,
  LEDGER_BACKUP_MODES,
  isLedgerBackupMode,
} from "./types.js";
export {
  CQ_CONFIG_FILENAME,
  CqConfigError,
  parseReviewerToken,
  formatReviewerToken,
  reviewerTokensEqual,
  parseConfig,
  assertDispatchable,
  resolveReviewers,
  resolvePlanners,
  resolveAgentTier,
  tierModel,
  applyAgentEffort,
  resolveAgentModel,
  loadConfig,
} from "./config.js";
export {
  resolveActiveHarness,
  resolveActiveHarnessFromProcess,
  DEFAULT_HARNESS,
  CQ_HARNESS_ENV,
  CLAUDE_CODE_SESSION_ID_ENV,
} from "./activeHarness.js";
export type {
  RawToml,
  RawWebui,
  RawLedger,
  RawProject,
  RawHarnessOverride,
} from "./toml.js";
export { parseToml } from "./toml.js";
export {
  CQ_LEDGER_REMOTE_TOKEN_ENV,
  RemoteLedgerTokenError,
  resolveRemoteLedgerToken,
  resolveRemoteLedgerTokenFromProcess,
} from "./remoteToken.js";
export type { AgentRoleTier } from "./agentRoster.js";
export { AGENT_ROLE_TIERS } from "./agentRoster.js";
export type {
  RoleKind,
  ModelTier,
  PromptSurface,
  IntentionalDifferenceKind,
  IntentionalDifferenceDeclaration,
  JSONSchema,
  JSONSchemaType,
  PromptCatalogEntry,
  RoleSchemaSidecar,
} from "./promptCatalog.js";
export {
  PROMPT_SURFACES,
  isPromptSurface,
  INTENTIONAL_DIFFERENCE_KINDS,
  isIntentionalDifferenceKind,
  INTENTIONAL_DIFFERENCE_DECLARATION_SCHEMA,
  PromptCatalogSchemaError,
  parseIntentionalDifferenceDeclaration,
  parseIntentionalDifferenceDeclarationJSON,
  serializeIntentionalDifferenceDeclaration,
} from "./promptCatalog.js";
export type {
  PromptFragmentSlot,
  PromptBlockClassification,
  PromptDispatchEdgeKind,
  PromptDispatchEdge,
  SharedPromptSourceBlock,
  FragmentPromptSourceBlock,
  PromptSourceBlock,
  PromptRoleSourceInventoryEntry,
  PromptFragmentSlotContract,
  ResolvedPromptFragmentInventoryEntry,
} from "./promptFragmentInventory.js";
export {
  PROMPT_FRAGMENT_SLOTS,
  PROMPT_BLOCK_CLASSIFICATIONS,
  PROMPT_DISPATCH_EDGE_KINDS,
  PROMPT_FRAGMENT_SLOT_CONTRACTS,
  PROMPT_ROLE_SOURCE_INVENTORY,
  PROMPT_FRAGMENT_INVENTORY,
  validatePromptFragmentInventory,
} from "./promptFragmentInventory.js";
export type {
  PromptCatalogFileInput,
  PromptFragmentFileInput,
  RenderPromptSurfaceTreeInput,
  RenderedPromptArtifact,
  RenderedPromptSurfaceTree,
} from "./promptRenderer.js";
export { PromptRendererError, renderPromptSurfaceTree } from "./promptRenderer.js";
export type {
  PromptVerificationRoot,
  PromptFragmentObservation,
  PromptCatalogVerificationInput,
} from "./promptCatalogVerification.js";
export {
  PromptCatalogVerificationError,
  verifyPromptCatalog,
} from "./promptCatalogVerification.js";
export { planAdvanceSidecar, PLAN_STEP_ACTIONS } from "./schemas/plan-advance.js";
export { planReviewerSidecar, PLAN_REVIEW_VERDICTS } from "./schemas/plan-reviewer.js";
export {
  implementWorkerSidecar,
  IMPLEMENT_WORKER_STATUSES,
  TEST_GUARD_GLOBS,
} from "./schemas/implement-worker.js";
export {
  implementReviewerSidecar,
  IMPLEMENT_REVIEW_VERDICTS,
} from "./schemas/implement-reviewer.js";
export {
  implementConflictResolverSidecar,
  CONFLICT_RESOLVER_STATUSES,
} from "./schemas/implement-conflict-resolver.js";
export { investigateExplorerSidecar } from "./schemas/investigate-explorer.js";
export { investigateProberSidecar } from "./schemas/investigate-prober.js";
export { EVIDENCE_LEANS } from "./schemas/investigate-evidence.js";
export {
  DISPATCHED_ROLE_SIDECARS,
  DISPATCHED_ROLE_IDS,
  DISPATCHED_ROLE_VERSIONS,
  getRoleSidecar,
} from "./promptCatalogStore.js";
export type { ValidationError, ValidationResult } from "./validation.js";
export { validateAgainstSchema } from "./validation.js";
export type {
  DispatchedRoleId,
  DispatchJSONValue,
  DispatchOverlayApplication,
  CompactDispatchLaunch,
  DispatchHandle,
  ResultCapability,
  DispatchPromptProvenance,
  DispatchDeadlines,
  DispatchPrepared,
  StoreDispatchResult,
  NativeCompletionProof,
  ConfirmDispatchCompletion,
  DispatchAbortReason,
  AbortDispatch,
  DispatchLifecycleState,
  PreparedDispatchResult,
  ResultStoredDispatchResult,
  ConsumedDispatchResult,
  AbortedDispatchResult,
  TerminalEnvelopeExpiredDispatchResult,
  AttestationNotFoundDispatchResult,
  FetchDispatchResult,
  DispatchProtocolOperation,
} from "./compactDispatchProtocol.js";
export {
  DISPATCH_ABORT_REASONS,
  DISPATCH_LIFECYCLE_STATES,
  DISPATCH_PROTOCOL_OPERATIONS,
  COMPACT_DISPATCH_LAUNCH_SCHEMA,
  compactDispatchLaunchSchemaFor,
  DISPATCH_HANDLE_SCHEMA,
  DISPATCH_PREPARED_SCHEMA,
  STORE_DISPATCH_RESULT_SCHEMA,
  CONFIRM_DISPATCH_COMPLETION_SCHEMA,
  ABORT_DISPATCH_SCHEMA,
  FETCH_DISPATCH_RESULT_SCHEMA,
} from "./compactDispatchProtocol.js";
export type {
  DispatchOverlayDefinition,
  DispatchOverlayRegistry,
  DispatchPromptMaterializationInput,
  DispatchPromptMaterialization,
} from "./dispatchOverlays.js";
export {
  DispatchOverlayError,
  createDispatchOverlayRegistry,
  DISPATCH_OVERLAY_REGISTRY,
  dispatchOverlayListSchema,
  materializeDispatchPrompt,
  validateDispatchOverlayApplications,
} from "./dispatchOverlays.js";
export type {
  DispatchPreLaunchRejectionReason,
  DispatchPreLaunchRejection,
  PreLaunchRejectionOutcomeIsNotALifecycleState,
  DispatchInputAccepted,
  DispatchInputValidation,
  DispatchPrepareStep,
  ValidateInputInspectionCaller,
  DispatchOutcomeTagClass,
  ChildSideValidationException,
  ChildSideValidationExceptionRegistry,
  DispatchInputValidatorPlacement,
  DispatchInputValidatorClaim,
  InsidePrepareValidatorResolution,
  ChildSideValidatorResolution,
  DispatchInputValidatorResolution,
  DispatchInputValidationRequest,
} from "./dispatchInputValidation.js";
export {
  DispatchInputValidationError,
  DISPATCH_PRE_LAUNCH_OUTCOME,
  DISPATCH_PRE_LAUNCH_REJECTION_REASONS,
  DISPATCH_INPUT_VALIDATION_PLACEMENT,
  DISPATCH_PREPARE_VALIDATION_STEPS,
  DISPATCH_PREPARE_ALLOCATION_STEPS,
  DISPATCH_PREPARE_STEP_ORDER,
  assertValidateThenAllocate,
  RETAINED_NON_FLOW_MCP_VALIDATORS,
  VALIDATE_INPUT_INSPECTION_CALLERS,
  isAllowlistedValidateInputCaller,
  classifyDispatchOutcomeTag,
  isDispatchPreLaunchRejection,
  createChildSideValidationExceptionRegistry,
  CHILD_SIDE_VALIDATION_EXCEPTIONS,
  DISPATCH_INPUT_VALIDATOR_PLACEMENTS,
  resolveDispatchInputValidator,
  validateDispatchInput,
  DISPATCH_INPUT_VALIDATION_DEFERRED_TO,
  DISPATCH_INPUT_VALIDATION_DEFERRED,
  dispatchPreLaunchRejection,
} from "./dispatchInputValidation.js";
export type {
  DispatchWorktreeCoordinates,
  ParentGuidanceKind,
  AnsweredQuestionGuidance,
  OperatorNoteGuidance,
  ParentGuidance,
  DispatchInputRefs,
  RefAssembledRoleId,
  CompactDispatchRefsLaunch,
  DispatchNarrativeItem,
  DispatchNarrativeSource,
  DispatchInputAssembled,
  DispatchInputAssembly,
  DispatchAssemblyContext,
} from "./dispatchRefAssembly.js";
export {
  DispatchRefAssemblyError,
  canonicalDispatchInputBytes,
  dispatchInputDigest,
  REFS_SUPPLIED_INPUT_FIELDS,
  ASSEMBLED_NARRATIVE_FIELDS,
  readNarrativeField,
  assembledNarrativeFieldsFor,
  PARENT_GUIDANCE_KINDS,
  PARENT_GUIDANCE_MAX_ENTRIES,
  PARENT_GUIDANCE_NOTE_MAX_LENGTH,
  DISPATCH_INPUT_REFS_FIELDS,
  REF_ASSEMBLED_ROLES,
  REF_ASSEMBLER_COVERAGE,
  DISPATCH_INPUT_REFS_SCHEMA,
  compactDispatchRefsLaunchSchemaFor,
  COMPACT_DISPATCH_REFS_LAUNCH_SCHEMA,
  REF_ASSEMBLY_LEDGERS,
  foldAnsweredQuestion,
  foldOperatorNote,
  assembleDispatchInput,
  isDispatchInputAssembled,
  ROLE_PROMPT_RETRIEVAL_OPERATIONS,
  NATIVE_CLAUDE_CHILD_RETRIEVAL,
  assertNoRolePromptRetrieval,
  DISPATCH_REF_ASSEMBLY_DEFERRED_TO,
  DISPATCH_REF_ASSEMBLY_DEFERRED,
} from "./dispatchRefAssembly.js";
export type {
  AttestationNamespace,
  DispatchAuthorizationScope,
  TrustedDispatchActor,
  StoreResultCannotName,
  DispatchRandomBytes,
  AttestationEnvelopeState,
  AttestationTerminalKind,
  NativeChildIdentity,
  DispatchProvenanceBinding,
  AttestationEnvelope,
  AttestationTombstone,
  AttestationRow,
  AttestationSweepReport,
  AttestationStore,
  DispatchNow,
  DispatchServiceDeps,
  PrepareDispatchDeps,
  PrepareDispatchRequest,
  DispatchPrepareAccepted,
  PrepareDispatchOutcome,
  StoreDispatchResultOutcome,
  StoredDispatchResultView,
  InvalidOutputAbortDetails,
  ConfirmDispatchCompletionRequest,
  ConfirmDispatchCompletionOutcome,
  ConfirmedDispatchResultView,
  FetchDispatchResultRequest,
  AbortDispatchRequest,
} from "./dispatchAttestation.js";
export {
  AttestationContractError,
  AttestationNamespaceError,
  DispatchAuthorizationError,
  AttestationBindingError,
  AttestationNotFoundError,
  DispatchStateConflictError,
  AttestationStorageError,
  AttestationTransportError,
  AttestationKeyReuseError,
  ATTESTATION_ERROR_CLASSES,
  isAttestationDomainError,
  assertAttestationNamespace,
  attestationNamespacesEqual,
  formatAttestationNamespace,
  TERMINAL_ENVELOPE_RETENTION_MS,
  IDEMPOTENCY_HORIZON_MS,
  DISPATCH_TIMEOUT_MIN_MS,
  DISPATCH_TIMEOUT_MAX_MS,
  RESPONSE_STORE_LEAD_MS,
  LAUNCH_DEADLINE_MS,
  ATTESTATION_ID_ENTROPY_BYTES,
  RESULT_CAPABILITY_ENTROPY_BYTES,
  DISPATCH_AUTHORIZATION_SCOPES,
  TRUSTED_DISPATCH_ACTORS,
  DISPATCH_OPERATION_AUTHORIZATION,
  DISPATCH_OPERATION_AUTHORIZATION_COVERAGE,
  assertDispatchOperationAuthorization,
  RESULT_CAPABILITY_OPERATIONS,
  dispatchOperationScope,
  resultCapabilityAuthorizes,
  dispatchPayloadDigest,
  resultCapabilityHash,
  resultCapabilityMatches,
  defaultDispatchRandomBytes,
  mintAttestationId,
  mintResultCapability,
  ATTESTATION_ENVELOPE_STATES,
  TOMBSTONE_RETAINED_FIELDS,
  TOMBSTONE_FORBIDDEN_FIELDS,
  isAttestationTombstone,
  attestationRowDigest,
  attestationInstantMs,
  assertDispatchHandle,
  prepareDispatch,
  storeDispatchResult,
  invalidOutputDetailsOf,
  confirmDispatchCompletion,
  provenanceBindingOf,
  abortDispatch,
  fetchDispatchResult,
  collapseAttestationEnvelope,
  sweepAttestations,
  DISPATCH_ATTESTATION_DEFERRED_TO,
  DISPATCH_ATTESTATION_DEFERRED,
  DISPATCH_ATTESTATION_MCP_DEFERRED_TO,
} from "./dispatchAttestation.js";
// --- T690: the Codex-surface binding of the compact dispatch protocol ------
export type {
  CodexDeliveryMode,
  CodexDeliveryModeVerdict,
  CodexChildCorrelation,
  CodexLaunchRefusal,
  CodexLaunchApproved,
  CodexLaunchRefused,
  CodexLaunchVerdict,
  CodexFinalMessageVerdictKind,
  CodexFinalMessageVerdict,
  CodexChildOutcome,
  CodexExitCorroboration,
  CodexCompletionObservation,
  CodexConfirmDecision,
  CodexAbortDecision,
  CodexCompletionDecision,
  CodexCompletionRequest,
} from "./codexDispatchProtocol.js";
export {
  CodexUnsupportedModeError,
  CodexObservationProvenanceError,
  CODEX_DELIVERY_MODE_IDS,
  CODEX_DELIVERY_MODES,
  SUPPORTED_CODEX_DELIVERY_MODES,
  UNSUPPORTED_CODEX_DELIVERY_MODES,
  CODEX_NATIVE_DELIVERY_MODE,
  CODEX_FALLBACK_DELIVERY_MODE,
  isSupportedCodexDeliveryMode,
  assertSupportedCodexDeliveryMode,
  codexCompletionActor,
  CODEX_ROLE_DELIVERY_PREREQUISITES,
  CODEX_ROLE_DELIVERY_PREREQUISITES_ARE_ATOMIC,
  CODEX_ROLE_DELIVERY_MIGRATION_OWNER,
  CODEX_GLOBAL_AGENTS_DIR,
  CODEX_NATIVE_AGENT_DECLARATION_KEYS,
  CODEX_CORRELATION_ENTROPY_BYTES,
  CODEX_CORRELATION_SEPARATOR,
  mintCodexCorrelationId,
  assertCodexChildCorrelation,
  codexExpectedChild,
  CODEX_LAUNCH_REFUSALS,
  codexLaunchGate,
  CODEX_FINAL_MESSAGE_VERDICTS,
  classifyCodexFinalMessage,
  CODEX_CHILD_OUTCOMES,
  CODEX_EXIT_CORROBORATIONS,
  decideCodexCompletion,
  codexExitCorroboration,
  CODEX_DISPATCH_DEFERRED_TO,
  CODEX_DISPATCH_DEFERRED,
} from "./codexDispatchProtocol.js";

export type { AttestationStoreOperation, AttestationStoreFault } from "./dispatchAttestationDummy.js";
export {
  ATTESTATION_STORE_OPERATIONS,
  InMemoryAttestationStore,
  InMemoryAttestationBackend,
  FakeDispatchClock,
  sequentialDispatchRandomBytes,
} from "./dispatchAttestationDummy.js";

// --- T720: the namespaced production AttestationStore adapters -------------
export { AsyncMutex } from "./asyncMutex.js";
export type {
  AttestationStoreBackend,
  AttestationExcludedBackend,
  AttestationLoadScope,
  AttestationLoadScopeKind,
  AttestationJournalEntry,
  AttestationBackend,
  AttestationBackendIO,
  AttestationBackendDeps,
  AttestationBackendPrepareDeps,
  AttestationSweepTimer,
  AttestationSweepScheduleOptions,
  PersistedAttestationRow,
} from "./dispatchAttestationBackend.js";
export {
  ATTESTATION_STORE_BACKENDS,
  ATTESTATION_EXCLUDED_BACKENDS,
  ATTESTATION_EXCLUSION_REASONS,
  ATTESTATION_IN_MEMORY_BACKEND,
  ATTESTATION_BACKEND_COVERAGE,
  ATTESTATION_DEFERRAL_DISCHARGE,
  ATTESTATION_DEFERRAL_COVERAGE,
  assertAttestationDeferralDischarge,
  ATTESTATION_LOAD_SCOPE_KINDS,
  ATTESTATION_TABLE,
  PERSISTED_ATTESTATION_COLUMNS,
  AttestationBackendUnsupportedError,
  AttestationSweepScheduler,
  BufferedAttestationStore,
  abortDispatchOn,
  applyJournalToStore,
  assertAttestationBackendCoverage,
  assertAttestationStoreBackend,
  assertAttestationStoreNamespace,
  attestationStorageKey,
  confirmDispatchCompletionOn,
  defaultAttestationSweepTimer,
  fetchDispatchResultOn,
  formatAttestationNamespaceLockKey,
  handleLoadScope,
  journalEntryHandle,
  loadScopeFromStore,
  persistAttestationRow,
  prepareDispatchOn,
  prepareLoadScope,
  rehydrateAttestationRow,
  runAttestationUnitOfWork,
  storeDispatchResultOn,
  storeResultLoadScope,
  sweepAttestationsOn,
} from "./dispatchAttestationBackend.js";
export type { SqliteAttestationBackendOptions } from "./dispatchAttestationSqlite.js";
export {
  ATTESTATION_BUSY_TIMEOUT_MS,
  ATTESTATION_DB_FILENAME,
  SqliteAttestationBackend,
  asSqliteBackendError,
  ensureAttestationSchema,
  xdgAttestationDbPath,
  xdgAttestationStateBase,
} from "./dispatchAttestationSqlite.js";
export type { FsAttestationBackendOptions } from "./dispatchAttestationFs.js";
export {
  ATTESTATION_LOCKS_DIR,
  ATTESTATION_LOCK_POLL_MS,
  ATTESTATION_LOCK_TIMEOUT_MS,
  FsAttestationBackend,
  asFsBackendError,
  fsAttestationNamespaceDir,
  fsAttestationRowFileContent,
  fsAttestationRowPath,
} from "./dispatchAttestationFs.js";
export type { PostgresAttestationBackendOptions } from "./dispatchAttestationPostgres.js";
export {
  PostgresAttestationBackend,
  asPgBackendError,
  ensurePgAttestationSchema,
  openAttestationPgPool,
} from "./dispatchAttestationPostgres.js";
