/**
 * T796 — stores created before the canonical `upstream` ledger existed gain it
 * additively on their next init. Fixtures are immutable artifacts generated by
 * T794's first parent, 9ad31c918fac51ef20fa48e4a9eaaeca28f9dbb3. Current
 * initialization code never participates in constructing legacy state.
 *
 * Shared assertions are Behavioral-Active Blackbox. Adapter-specific raw
 * comparisons are Graybox checks of persisted rows, counters, archives, and
 * log artifacts.
 */

import { afterAll, describe, expect, test } from "bun:test";
import type { SQL } from "bun";
import { execFile } from "node:child_process";
import { randomUUID } from "node:crypto";
import { copyFile, cp, mkdtemp, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import * as path from "node:path";
import { promisify } from "node:util";
import {

  buildBackupDump,
  CANONICAL_LEDGERS,
  FsLedgerStore,
  GitObjectLedgerBackend,
  GitPlumbing,
  GOALS_LEDGER,
  IDEAS_LEDGER,
  InMemoryLedgerStore,
  LEDGER_STORAGE_DIRNAME,
  OPERATOR_ACTIONS_LEDGER,
  parseRegistry,
  PLAN_MANAGED_GOAL_FIELD_NAMES,
  PLAN_REVIEW_DRAFT_FIELD,
  WORKSET_OWNED_FIELD_NAMES,
  PostgresLedgerStore,
  removeLedgerArtifacts,
  restoreDumpToXdg,
  REVIEWS_LEDGER,
  SqliteLedgerStore,
  UPSTREAM_LEDGER,
  UPSTREAM_SCHEMA,
  type ArchiveContent,
  type BackupDumpFile,
  type FetchedLedger,
  type Ledger,
  type LedgerSchema,
  type LedgerStore,
  mintWorksetManagementAuthority,
} from "../src/index.js";
import { openPgPool } from "../src/store/postgres/connection.js";
import { ensureSchema as ensurePostgresSchema } from "../src/store/postgres/schema.js";
import { openLedgerDb } from "../src/store/sqlite/connection.js";

const exec = promisify(execFile);
const FIXTURE_REVISION = "9ad31c918fac51ef20fa48e4a9eaaeca28f9dbb3";
const FIXTURE_DIR = path.join(import.meta.dir, "fixtures", "pre-upstream-9ad31c9");
const FS_FIXTURE_ROOT = path.join(FIXTURE_DIR, "fs-root");
const SQLITE_FIXTURE_DB = path.join(FIXTURE_DIR, "xdg", "ledger.db");
const SQLITE_FIXTURE_LOGS = path.join(FIXTURE_DIR, "xdg", "logs");
const GIT_FIXTURE_BUNDLE = path.join(FIXTURE_DIR, "git-object.bundle");
const MEMORY_FIXTURE = path.join(FIXTURE_DIR, "in-memory.json");
const POSTGRES_FIXTURE = path.join(FIXTURE_DIR, "postgres.sql");
const EXPECTED_PUBLIC_FIXTURE = path.join(FIXTURE_DIR, "expected-public.json");
const FIXED_NOW = "2026-07-25T06:00:00.000Z";
const now = (): string => FIXED_NOW;
const GIT_REF = "refs/heads/cq-ledger";
const PG_URL = process.env.CQ_TEST_PG_URL;
const SESSION_LOG_REF = ".cq/logs/20260724-legacy-session.md";
const RAW_LOG_REF = ".cq/logs/raw/20260724-legacy-worker.jsonl";
const LOG_PATHS = ["20260724-legacy-session.md", "raw/20260724-legacy-worker.jsonl"] as const;

const roots: string[] = [];
afterAll(async () => {
  await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true })));
});

const PRE_UPSTREAM_NAMES = CANONICAL_LEDGERS.filter(({ name }) => name !== UPSTREAM_LEDGER)
  .filter(({ name }) => name !== OPERATOR_ACTIONS_LEDGER)
  .map(({ name }) => name)
  .sort();
const CURRENT_NAMES = CANONICAL_LEDGERS.map(({ name }) => name).sort();
const POST_FIXTURE_LEDGER_NAMES: ReadonlySet<string> = new Set([
  OPERATOR_ACTIONS_LEDGER,
  UPSTREAM_LEDGER,
]);
const POST_FIXTURE_CANONICAL_LEDGERS = CANONICAL_LEDGERS.filter(({ name }) =>
  POST_FIXTURE_LEDGER_NAMES.has(name),
);

type PublicSnapshot = Record<string, FetchedLedger>;

interface FrozenPublicFixture {
  readonly sourceRevision: string;
  readonly ledgers: PublicSnapshot;
  readonly archives: Record<string, ArchiveContent>;
}

interface FrozenMemoryFixture {
  readonly sourceRevision: string;
  readonly ledgers: Array<[string, Ledger]>;
  readonly archives: Array<[string, unknown]>;
  readonly itemArchives: Array<[string, unknown]>;
  readonly logs: ReadonlyArray<{ path: string; content: string }>;
}

interface LogReadableStore {
  readLog(path: string): Promise<{ path: string; content: string; truncated?: true }>;
}

const expectedPublicFixture = readFile(EXPECTED_PUBLIC_FIXTURE, "utf8").then(
  (content) => JSON.parse(content) as FrozenPublicFixture,
);
const memoryFixture = readFile(MEMORY_FIXTURE, "utf8").then(
  (content) => JSON.parse(content) as FrozenMemoryFixture,
);
const expectedLogState = captureLogFiles(SQLITE_FIXTURE_LOGS);

function publicSnapshot(store: LedgerStore, names: readonly string[]): PublicSnapshot {
  return Object.fromEntries(names.map((name) => [name, structuredClone(store.fetch(name))]));
}

function withoutPlanLifecycleSchemaFields(snapshot: PublicSnapshot): PublicSnapshot {
  const compatible = structuredClone(snapshot);
  for (const ledger of Object.values(compatible)) {
    for (const field of WORKSET_OWNED_FIELD_NAMES) delete ledger.schema.fields[field];
  }
  const goals = compatible[GOALS_LEDGER];
  if (goals !== undefined) {
    for (const field of PLAN_MANAGED_GOAL_FIELD_NAMES) delete goals.schema.fields[field];
  }
  const reviews = compatible[REVIEWS_LEDGER];
  if (reviews !== undefined) delete reviews.schema.fields[PLAN_REVIEW_DRAFT_FIELD];
  const ideas = compatible[IDEAS_LEDGER];
  if (ideas !== undefined) delete ideas.schema.fields.ledgerRefs;
  return compatible;
}

function withoutPlanLifecycleFields(
  ledgerName: string,
  schema: LedgerSchema,
): LedgerSchema {
  const compatible = structuredClone(schema);
  for (const field of WORKSET_OWNED_FIELD_NAMES) delete compatible.fields[field];
  if (ledgerName === GOALS_LEDGER) {
    for (const field of PLAN_MANAGED_GOAL_FIELD_NAMES) delete compatible.fields[field];
  }
  if (ledgerName === REVIEWS_LEDGER) delete compatible.fields[PLAN_REVIEW_DRAFT_FIELD];
  if (ledgerName === IDEAS_LEDGER) delete compatible.fields.ledgerRefs;
  return compatible;
}

function withoutPlanLifecycleSchemaRows(
  rows: Array<Record<string, unknown>>,
): Array<Record<string, unknown>> {
  return rows.map((row) => {
    const name = row["name"];
    const storedSchema = row["schema_json"];
    if (
      typeof name !== "string" ||
      (typeof storedSchema !== "string" &&
        (storedSchema === null || typeof storedSchema !== "object"))
    ) {
      throw new Error("invalid captured ledger schema row");
    }
    const schema =
      typeof storedSchema === "string"
        ? (JSON.parse(storedSchema) as LedgerSchema)
        : (storedSchema as LedgerSchema);
    const compatible = withoutPlanLifecycleFields(name, schema);
    return {
      ...row,
      schema_json:
        typeof storedSchema === "string" ? JSON.stringify(compatible) : compatible,
    };
  });
}

async function assertAdditivePublicState(
  store: LedgerStore,
  expected: FrozenPublicFixture,
): Promise<void> {
  expect(store.enumerate().sort()).toEqual(CURRENT_NAMES);
  expect(withoutPlanLifecycleSchemaFields(publicSnapshot(store, PRE_UPSTREAM_NAMES))).toEqual(
    expected.ledgers,
  );

  for (const [key, archive] of Object.entries(expected.archives)) {
    const separator = key.indexOf("/");
    if (separator < 1) throw new Error(`invalid frozen archive key: ${key}`);
    const ledger = key.slice(0, separator);
    const pointer = key.slice(separator + 1);
    expect(await store.fetchArchive(ledger, pointer)).toEqual(archive);
  }

  for (const { name, schema } of POST_FIXTURE_CANONICAL_LEDGERS) {
    const additive = store.fetch(name);
    expect(additive.schema).toEqual(schema);
    expect(additive.counters).toEqual({ milestone: 0, item: 0 });
    expect(additive.milestones).toEqual([]);
    expect(additive.archivePointers).toEqual([]);
  }
}

async function assertLegacyLogs(store: LedgerStore): Promise<void> {
  if (!("readLog" in store)) {
    throw new Error("persistent fixture store does not expose readLog");
  }
  const readable = store as LedgerStore & LogReadableStore;
  const session = await readable.readLog(SESSION_LOG_REF);
  const raw = await readable.readLog(RAW_LOG_REF);
  expect(session).toEqual({
    path: SESSION_LOG_REF,
    content: "# Legacy session\n\nProduced before the upstream ledger existed.\n",
  });
  expect(raw).toEqual({
    path: RAW_LOG_REF,
    content: '{"type":"assistant","message":{"content":"legacy raw transcript"}}\n',
  });
}

interface PersistentFixture {
  readonly expected: FrozenPublicFixture;
  open(): LedgerStore;
  capturePriorRawState(): Promise<string>;
  captureCompleteRawState(): Promise<string>;
  assertNoDivergenceBackup(): Promise<void>;
}

async function runPersistentContract(fixture: PersistentFixture): Promise<void> {
  const rawBefore = await fixture.capturePriorRawState();

  const first = fixture.open();
  await first.init();
  try {
    await assertAdditivePublicState(first, fixture.expected);
    await assertLegacyLogs(first);
  } finally {
    await first.dispose();
  }

  expect(await fixture.capturePriorRawState()).toBe(rawBefore);
  await fixture.assertNoDivergenceBackup();
  const completeAfterFirst = await fixture.captureCompleteRawState();

  const second = fixture.open();
  await second.init();
  try {
    await assertAdditivePublicState(second, fixture.expected);
    await assertLegacyLogs(second);
  } finally {
    await second.dispose();
  }

  expect(await fixture.captureCompleteRawState()).toBe(completeAfterFirst);
  await fixture.assertNoDivergenceBackup();
}

async function freshRoot(prefix: string): Promise<string> {
  const root = await mkdtemp(path.join(tmpdir(), prefix));
  roots.push(root);
  return root;
}

async function relativeFiles(root: string, prefix: string): Promise<string[]> {
  const directory = path.join(root, prefix);
  const entries = await readdir(directory, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const relative = path.join(prefix, entry.name);
    if (entry.isDirectory()) files.push(...(await relativeFiles(root, relative)));
    else if (entry.isFile()) files.push(relative);
  }
  return files.sort();
}

async function captureFiles(root: string, paths: readonly string[]): Promise<string> {
  const contents = await Promise.all(
    paths.map(async (file) => [file, (await readFile(path.join(root, file))).toString("base64")]),
  );
  return JSON.stringify(contents);
}

async function captureLogFiles(logsDir: string): Promise<string> {
  return captureFiles(logsDir, LOG_PATHS);
}

async function frozenFsPaths(): Promise<string[]> {
  return relativeFiles(path.join(FS_FIXTURE_ROOT, LEDGER_STORAGE_DIRNAME), "");
}

async function captureFsPriorState(storageDir: string): Promise<string> {
  const paths = (await frozenFsPaths()).filter((file) => file !== "ledgers.yaml");
  const registry = parseRegistry(await readFile(path.join(storageDir, "ledgers.yaml"), "utf8"));
  return JSON.stringify({
    registry: registry.ledgers
      .filter(({ name }) => !POST_FIXTURE_LEDGER_NAMES.has(name))
      .map((entry) => ({
        ...entry,
        schema: withoutPlanLifecycleFields(entry.name, entry.schema),
      })),
    files: JSON.parse(await captureFiles(storageDir, paths)) as unknown,
  });
}

async function captureCompleteFsState(storageDir: string): Promise<string> {
  const paths = (await relativeFiles(storageDir, "")).filter(
    (file) => !file.startsWith(".backup/") && !file.startsWith(".locks/"),
  );
  return captureFiles(storageDir, paths);
}

async function prepareFsFixture(): Promise<PersistentFixture & { root: string }> {
  const expected = await expectedPublicFixture;
  const parent = await freshRoot("t796-fs-");
  const root = path.join(parent, "store");
  await cp(FS_FIXTURE_ROOT, root, { recursive: true });
  const storageDir = path.join(root, LEDGER_STORAGE_DIRNAME);

  expect(
    parseRegistry(await readFile(path.join(storageDir, "ledgers.yaml"), "utf8"))
      .ledgers.map(({ name }) => name)
      .sort(),
  ).toEqual(PRE_UPSTREAM_NAMES);

  return {
    root,
    expected,
    open: () => new FsLedgerStore({ root, now }),
    capturePriorRawState: () => captureFsPriorState(storageDir),
    captureCompleteRawState: () => captureCompleteFsState(storageDir),
    async assertNoDivergenceBackup() {
      await expect(stat(path.join(storageDir, ".backup"))).rejects.toMatchObject({
        code: "ENOENT",
      });
    },
  };
}

async function initGitRepository(): Promise<string> {
  const root = await freshRoot("t796-git-");
  await exec("git", ["init", "-q", root], { encoding: "utf8" });
  await exec("git", ["config", "user.email", "test@example.com"], { cwd: root });
  await exec("git", ["config", "user.name", "test"], { cwd: root });
  await writeFile(path.join(root, "host.txt"), "host checkout\n", "utf8");
  await exec("git", ["add", "host.txt"], { cwd: root });
  await exec("git", ["commit", "-q", "-m", "host: initial"], { cwd: root });
  await exec("git", ["fetch", GIT_FIXTURE_BUNDLE, `${GIT_REF}:${GIT_REF}`], {
    cwd: root,
    encoding: "utf8",
  });
  return root;
}

async function divergenceBackupTags(root: string): Promise<string[]> {
  const { stdout } = await exec("git", ["for-each-ref", "--format=%(refname)", "refs/tags"], {
    cwd: root,
    encoding: "utf8",
  });
  return stdout
    .split("\n")
    .filter((ref) => ref.startsWith("refs/tags/cq-ledger-backup-"))
    .sort();
}

async function captureGitState(
  git: GitPlumbing,
  legacyPaths: readonly string[],
  complete: boolean,
): Promise<string> {
  const paths = complete ? (await git.lsTree(GIT_REF)).sort() : [...legacyPaths].sort();
  const registry = parseRegistry(await git.catFile(GIT_REF, "ledgers.yaml"));
  const contents = await Promise.all(
    paths
      .filter((entry) => entry !== "ledgers.yaml")
      .map(async (entry) => [entry, await git.catFile(GIT_REF, entry)]),
  );
  return JSON.stringify({
    registry: complete
      ? registry.ledgers
      : registry.ledgers
          .filter(({ name }) => !POST_FIXTURE_LEDGER_NAMES.has(name))
          .map((entry) => ({
            ...entry,
            schema: withoutPlanLifecycleFields(entry.name, entry.schema),
          })),
    contents,
    ref: complete ? await git.readRef(GIT_REF) : null,
  });
}

async function prepareGitFixture(): Promise<PersistentFixture> {
  const expected = await expectedPublicFixture;
  const root = await initGitRepository();
  const git = GitPlumbing.withCwd(root, path.join(root, ".git"));
  const legacyPaths = await git.lsTree(GIT_REF);

  expect(
    parseRegistry(await git.catFile(GIT_REF, "ledgers.yaml"))
      .ledgers.map(({ name }) => name)
      .sort(),
  ).toEqual(PRE_UPSTREAM_NAMES);

  return {
    expected,
    open: () => new GitObjectLedgerBackend({ repoRoot: root, now }),
    capturePriorRawState: () => captureGitState(git, legacyPaths, false),
    captureCompleteRawState: () => captureGitState(git, legacyPaths, true),
    async assertNoDivergenceBackup() {
      expect(await divergenceBackupTags(root)).toEqual([]);
    },
  };
}

const SQLITE_TABLES = ["groups", "items", "archive_pointers", "archived_items", "meta"] as const;

async function captureSqliteState(
  dbPath: string,
  logsDir: string,
  includeUpstream: boolean,
): Promise<string> {
  const db = openLedgerDb(dbPath);
  try {
    const ledgerRows = includeUpstream
      ? db
          .query(
            "SELECT name, schema_json, milestone_counter, item_counter FROM ledgers ORDER BY rowid",
          )
          .all()
      : db
          .query(
            "SELECT name, schema_json, milestone_counter, item_counter FROM ledgers WHERE name NOT IN (?, ?) ORDER BY rowid",
          )
          .all(UPSTREAM_LEDGER, OPERATOR_ACTIONS_LEDGER);
    const ledgers = includeUpstream
      ? ledgerRows
      : withoutPlanLifecycleSchemaRows(
          ledgerRows as Array<Record<string, unknown>>,
        );
    const tables = Object.fromEntries(
      SQLITE_TABLES.map((table) => [
        table,
        db.query(`SELECT * FROM ${table} ORDER BY rowid`).all(),
      ]),
    );
    // T1509 (G155): the sanctioned v2→v3 in-place bump makes the
    // schema_version marker a moving target across store generations. The
    // byte-identity contract covers DATA, not the migration marker, so the
    // marker row is normalized to a constant before comparison.
    tables["meta"] = (tables["meta"] as Array<Record<string, unknown>>).map((row) =>
      row["key"] === "schema_version" ? { ...row, value: "MIGRATED" } : row,
    );
    return JSON.stringify({ ledgers, tables, logs: JSON.parse(await captureLogFiles(logsDir)) });
  } finally {
    db.close();
  }
}

async function prepareSqliteFixture(): Promise<PersistentFixture> {
  const expected = await expectedPublicFixture;
  const root = await freshRoot("t796-sqlite-");
  const dbPath = path.join(root, "ledger.db");
  const logsDir = path.join(root, "logs");
  await copyFile(SQLITE_FIXTURE_DB, dbPath);
  await cp(SQLITE_FIXTURE_LOGS, logsDir, { recursive: true });

  const db = openLedgerDb(dbPath);
  try {
    const names = (
      db.query("SELECT name FROM ledgers ORDER BY name").all() as Array<{ name: string }>
    ).map(({ name }) => name);
    expect(names).toEqual(PRE_UPSTREAM_NAMES);
  } finally {
    db.close();
  }

  return {
    expected,
    open: () => new SqliteLedgerStore({ dbPath, logsDir, now }),
    capturePriorRawState: () => captureSqliteState(dbPath, logsDir, false),
    captureCompleteRawState: () => captureSqliteState(dbPath, logsDir, true),
    async assertNoDivergenceBackup() {
      expect((await readdir(root)).filter((name) => name.includes(".backup-"))).toEqual([]);
    },
  };
}

async function capturePostgresState(
  pool: SQL,
  projectKey: string,
  includeUpstream: boolean,
): Promise<string> {
  const projects = await pool<Array<Record<string, unknown>>>`
    SELECT project_key, display_name, created_at::text, updated_at::text
    FROM projects WHERE project_key = ${projectKey}
  `;
  const ledgerRows = includeUpstream
    ? await pool<Array<Record<string, unknown>>>`
        SELECT name, schema_json, milestone_counter, item_counter
        FROM ledgers WHERE project_key = ${projectKey} ORDER BY name
      `
    : await pool<Array<Record<string, unknown>>>`
        SELECT name, schema_json, milestone_counter, item_counter
        FROM ledgers
        WHERE project_key = ${projectKey}
          AND name <> ${UPSTREAM_LEDGER}
          AND name <> ${OPERATOR_ACTIONS_LEDGER}
        ORDER BY name
      `;
  const ledgers = includeUpstream
    ? ledgerRows
    : withoutPlanLifecycleSchemaRows(ledgerRows);
  const groups = await pool<Array<Record<string, unknown>>>`
    SELECT seq::text, ledger, id, title, description
    FROM groups WHERE project_key = ${projectKey} ORDER BY seq
  `;
  const items = await pool<Array<Record<string, unknown>>>`
    SELECT seq::text, ledger, id, milestone_id, status, fields_json,
           created_at, updated_at, author, session
    FROM items WHERE project_key = ${projectKey} ORDER BY seq
  `;
  const pointers = await pool<Array<Record<string, unknown>>>`
    SELECT seq::text, ledger, id, summary, title, status, archived_at
    FROM archive_pointers WHERE project_key = ${projectKey} ORDER BY seq
  `;
  const archived = await pool<Array<Record<string, unknown>>>`
    SELECT seq::text, ledger, pointer_id, id, milestone_id, status, fields_json,
           created_at, updated_at, author, session
    FROM archived_items WHERE project_key = ${projectKey} ORDER BY seq
  `;
  const logs = await pool<Array<Record<string, unknown>>>`
    SELECT path, content, created_at::text
    FROM logs WHERE project_key = ${projectKey} ORDER BY path
  `;
  return JSON.stringify({ projects, ledgers, groups, items, pointers, archived, logs });
}

async function cleanupPostgresTenantFamily(pool: SQL, projectKey: string): Promise<void> {
  const tenants = await pool<Array<{ project_key: string }>>`
    SELECT project_key FROM projects
    WHERE project_key = ${projectKey}
       OR project_key LIKE ${`${projectKey}__divergence-backup-%`}
    ORDER BY project_key
  `;
  for (const { project_key: tenant } of tenants) {
    await pool.begin(async (tx) => {
      await tx`DELETE FROM archived_items WHERE project_key = ${tenant}`;
      await tx`DELETE FROM archive_pointers WHERE project_key = ${tenant}`;
      await tx`DELETE FROM items WHERE project_key = ${tenant}`;
      await tx`DELETE FROM groups WHERE project_key = ${tenant}`;
      await tx`DELETE FROM ledgers WHERE project_key = ${tenant}`;
      await tx`DELETE FROM logs WHERE project_key = ${tenant}`;
      await tx`DELETE FROM projects WHERE project_key = ${tenant}`;
    });
  }
}

async function preparePostgresFixture(
  setupPool: SQL,
  postgresUrl: string,
  projectKey: string,
): Promise<PersistentFixture> {
  const expected = await expectedPublicFixture;
  await ensurePostgresSchema(setupPool);
  const sql = (await readFile(POSTGRES_FIXTURE, "utf8")).replaceAll("__PROJECT_KEY__", projectKey);
  for (const statement of sql.split(/;\s*\n/)) {
    const query = statement.trim();
    if (query.length > 0) await setupPool.unsafe(query);
  }

  const names = await setupPool<Array<{ name: string }>>`
    SELECT name FROM ledgers WHERE project_key = ${projectKey} ORDER BY name
  `;
  expect(names.map(({ name }) => name)).toEqual(PRE_UPSTREAM_NAMES);

  return {
    expected,
    open: () =>
      new PostgresLedgerStore({
        pool: openPgPool(postgresUrl),
        projectKey,
        displayName: "Legacy pre-upstream fixture",
        now,
      }),
    capturePriorRawState: () => capturePostgresState(setupPool, projectKey, false),
    captureCompleteRawState: () => capturePostgresState(setupPool, projectKey, true),
    async assertNoDivergenceBackup() {
      const shadows = await setupPool<Array<{ project_key: string }>>`
        SELECT project_key FROM projects
        WHERE project_key LIKE ${`${projectKey}__divergence-backup-%`}
      `;
      expect(shadows).toEqual([]);
    },
  };
}

function normalizeDump(dump: readonly BackupDumpFile[]): BackupDumpFile[] {
  return [...dump].sort((left, right) => left.path.localeCompare(right.path));
}

describe("pre-upstream immutable fixture provenance", () => {
  test("fixtures came from T794's first parent and contain archived data plus logs", async () => {
    const manifest = JSON.parse(
      await readFile(path.join(FIXTURE_DIR, "manifest.json"), "utf8"),
    ) as {
      sourceRevision: string;
    };
    const expected = await expectedPublicFixture;
    const memory = await memoryFixture;

    expect(manifest.sourceRevision).toBe(FIXTURE_REVISION);
    expect(expected.sourceRevision).toBe(FIXTURE_REVISION);
    expect(memory.sourceRevision).toBe(FIXTURE_REVISION);
    expect(Object.keys(expected.ledgers).sort()).toEqual(PRE_UPSTREAM_NAMES);
    expect(expected.archives["tasks/M42"]).toEqual({
      kind: "group",
      milestone: expect.objectContaining({
        id: "M42",
        items: [expect.objectContaining({ id: "T52" })],
      }),
    });
    expect(memory.logs.map(({ path: logPath }) => logPath).sort()).toEqual(
      [RAW_LOG_REF, SESSION_LOG_REF].sort(),
    );
    expect(await captureLogFiles(path.join(FS_FIXTURE_ROOT, ".cq", "logs"))).toBe(
      await expectedLogState,
    );
  });

  test("git divergence-tag oracle detects and can isolate a matching sentinel", async () => {
    const root = await initGitRepository();
    const sentinel = "cq-ledger-backup-sentinel";
    const sentinelRef = `refs/tags/${sentinel}`;
    await exec("git", ["tag", sentinel], { cwd: root });
    try {
      expect(await divergenceBackupTags(root)).toEqual([sentinelRef]);
    } finally {
      await exec("git", ["tag", "--delete", sentinel], { cwd: root });
    }
    expect(await divergenceBackupTags(root)).toEqual([]);
  });
});

describe("pre-upstream canonical-ledger initialization", () => {
  test("FsLedgerStore adds only an empty upstream ledger and a second init is idempotent", async () => {
    await runPersistentContract(await prepareFsFixture());
  });

  test("GitObjectLedgerBackend adds only an empty upstream ledger without a divergence tag", async () => {
    await runPersistentContract(await prepareGitFixture());
  }, 30_000);

  test("SqliteLedgerStore adds only an empty upstream row transactionally", async () => {
    await runPersistentContract(await prepareSqliteFixture());
  });

  test("InMemoryLedgerStore hydrates the frozen serialized seed additively", async () => {
    const expected = await expectedPublicFixture;
    const frozen = await memoryFixture;
    const store = new InMemoryLedgerStore({ now });
    const fixtureState = store as unknown as {
      ledgers: Map<string, Ledger>;
      archives: Map<string, unknown>;
      itemArchives: Map<string, unknown>;
      initialised: boolean;
    };
    fixtureState.ledgers = new Map(structuredClone(frozen.ledgers));
    fixtureState.archives = new Map(structuredClone(frozen.archives));
    fixtureState.itemArchives = new Map(structuredClone(frozen.itemArchives));
    fixtureState.initialised = false;
    const priorBytes = JSON.stringify({
      ledgers: frozen.ledgers,
      archives: frozen.archives,
      itemArchives: frozen.itemArchives,
      logs: frozen.logs,
    });

    await store.init();
    await assertAdditivePublicState(store, expected);
    expect(
      JSON.stringify({
        ledgers: Array.from(fixtureState.ledgers.entries()).filter(
          ([name]) => !POST_FIXTURE_LEDGER_NAMES.has(name),
        ),
        archives: Array.from(fixtureState.archives.entries()),
        itemArchives: Array.from(fixtureState.itemArchives.entries()),
        logs: frozen.logs,
      }),
    ).toBe(priorBytes);
    const afterFirst = JSON.stringify(Array.from(fixtureState.ledgers.entries()));

    await store.init();
    await assertAdditivePublicState(store, expected);
    expect(JSON.stringify(Array.from(fixtureState.ledgers.entries()))).toBe(afterFirst);
    await store.dispose();
  });
});

describe.skipIf(!PG_URL)("pre-upstream PostgreSQL tenant initialization", () => {
  const setupPool = PG_URL === undefined ? undefined : openPgPool(PG_URL);
  const tenantKeys = new Set<string>();

  afterAll(async () => {
    if (setupPool === undefined) return;
    for (const projectKey of tenantKeys) {
      await cleanupPostgresTenantFamily(setupPool, projectKey);
    }
    tenantKeys.clear();
    await setupPool.close();
  });

  test("PostgresLedgerStore adds only an empty tenant-scoped upstream row", async () => {
    if (setupPool === undefined || PG_URL === undefined) {
      throw new Error("PostgreSQL fixture test ran without CQ_TEST_PG_URL");
    }
    const projectKey = `t796-${randomUUID()}`;
    tenantKeys.add(projectKey);
    try {
      const fixture = await preparePostgresFixture(setupPool, PG_URL, projectKey);
      await runPersistentContract(fixture);
    } finally {
      await cleanupPostgresTenantFamily(setupPool, projectKey);
      tenantKeys.delete(projectKey);
    }
  }, 30_000);
});

describe("pre-upstream lifecycle acceptance states", () => {
  test("portable backup and XDG restore preserve every upgraded datum and log byte", async () => {
    const fixture = await prepareFsFixture();
    const source = fixture.open();
    await source.init();
    await assertAdditivePublicState(source, fixture.expected);
    const expected = publicSnapshot(source, CURRENT_NAMES);
    const sourceLogs = path.join(fixture.root, ".cq", "logs");
    const dump = await buildBackupDump(source, sourceLogs);
    await source.dispose();

    const registryFile = dump.find(({ path: file }) => file === "ledgers.yaml");
    if (registryFile === undefined) {
      throw new Error("Portable backup omitted ledgers.yaml");
    }
    const dumpedRegistry = parseRegistry(registryFile.content);
    expect(dumpedRegistry.ledgers).toContainEqual(
      expect.objectContaining({ name: UPSTREAM_LEDGER, schema: UPSTREAM_SCHEMA }),
    );
    expect(dump.map(({ path: file }) => file)).toEqual(
      expect.arrayContaining([
        `${UPSTREAM_LEDGER}.md`,
        "archive/tasks/M42.md",
        "archive/milestones/M42.md",
        "logs/20260724-legacy-session.md",
        "logs/raw/20260724-legacy-worker.jsonl",
      ]),
    );

    const destinationRoot = await freshRoot("t796-restore-");
    const dbPath = path.join(destinationRoot, "ledger.db");
    const logsDir = path.join(destinationRoot, "logs");
    await restoreDumpToXdg({
      dbPath,
      logsDir,
      dump,
      authority: mintWorksetManagementAuthority(),
      overwriteAuthorized: false,
    });
    const restored = new SqliteLedgerStore({ dbPath, logsDir, now });
    await restored.init();
    try {
      expect(publicSnapshot(restored, CURRENT_NAMES)).toEqual(expected);
      await assertAdditivePublicState(restored, fixture.expected);
      await assertLegacyLogs(restored);
      expect(normalizeDump(await buildBackupDump(restored, logsDir))).toEqual(normalizeDump(dump));
      const next = await restored.createItem(UPSTREAM_LEDGER, "M41", {
        status: "open",
        fields: {
          headline: "post-restore upstream report",
          package: "@cq/example",
        },
      });
      expect(next.id).toBe("U1");
    } finally {
      await restored.dispose();
    }
  });

  test("reset preserves legacy archive/log bytes, retains upstream canon, and erase removes it", async () => {
    const fixture = await prepareFsFixture();
    const store = fixture.open();
    await store.init();
    await store.createItem(UPSTREAM_LEDGER, "M41", {
      status: "open",
      fields: {
        headline: "reset target",
        package: "@cq/example",
      },
    });

    if (!(store instanceof FsLedgerStore)) {
      throw new Error("expected FsLedgerStore fixture");
    }
    const summary = await store.reset();
    expect(summary.ledgers).toContainEqual(
      expect.objectContaining({ name: UPSTREAM_LEDGER, itemCount: 1 }),
    );
    expect(store.enumerate()).toEqual(CURRENT_NAMES);
    expect(store.fetch(UPSTREAM_LEDGER).counters).toEqual({ milestone: 0, item: 0 });
    expect(store.fetch(UPSTREAM_LEDGER).milestones).toEqual([]);
    await store.dispose();

    const storageDir = path.join(fixture.root, LEDGER_STORAGE_DIRNAME);
    expect(await readFile(path.join(summary.backupDir, `${UPSTREAM_LEDGER}.md`), "utf8")).toContain(
      "# upstream",
    );
    const legacyArtifacts = [
      "archive/tasks/M42.md",
      "archive/milestones/M42.md",
      "logs/20260724-legacy-session.md",
      "logs/raw/20260724-legacy-worker.jsonl",
    ];
    expect(await captureFiles(storageDir, legacyArtifacts)).toBe(
      await captureFiles(path.join(FS_FIXTURE_ROOT, ".cq"), legacyArtifacts),
    );
    const erased = await removeLedgerArtifacts(storageDir);
    expect(erased.removed.some((entry) => entry.endsWith(`${UPSTREAM_LEDGER}.md`))).toBe(true);
    await expect(stat(storageDir)).rejects.toMatchObject({ code: "ENOENT" });
    expect((await readdir(fixture.root)).sort()).toEqual([]);
  });
});
